@Library('mylibrary')_
pipeline
{   
    agent any
    stages
    {
        stage('ContinousDownload')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/Nihal4577/mymavenn.git")
                }
            }
        }
         stage('ContinousBulid')
        {
            steps
            {
                script
                {
                  cicd.newMaven()
                }
            }
        }
     }
}
